version: "3.7"

services:
  api:
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
    restart: always
    networks:
        - traefik
        - internal_network
    ports:
        - ${API_PORT_OUT}:${API_PORT_IN}
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.${API_CONTAINER_NAME}.rule=Host(`${API_HOST}`)'
      - 'traefik.http.routers.${API_CONTAINER_NAME}.entrypoints=${TRAEFIK_API_ENTRYPOINT}'
    deploy:
      replicas: ${APP_REPLICAS}
    
  database:
    container_name: ${DB_CONTAINER_NAME}
    image : ${DB_IMAGE}
    ports:
      - ${DB_PORT_OUT}:${DB_PORT_IN}
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - internal_network
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
          

volumes:
  db-data:
    name: ${DB_VOLUME_NAME}
                

networks:
    traefik:
      name: ${TRAEFIK_NETWORK_NAME}
      external: true
    internal_network:

  